sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
before_script: "pip install setuptools-lint"
install: "pip install -r requirements.txt"
script: "python setup.py test lint"